export default Strings = {
    HOnboarding1: 'Convenient Telehealth: Virtual Consultations and Follow-up Anythime, Anywhere',
    HOnboarding2: 'Prescription Plus Your One-Stop Shop For Medicines, Equipment And More',
    HOnboarding3: 'Logistics And We\'ll Deliver It All Too, In Record Time',
    HOnboarding4: 'Inspire Your Medical Practice Through The Power Of Collaboration And Knowledge Sharing',
    HRegisterTitle: 'Register Account',
    HLoginTitle: 'Hello Dr!',
    HAuthSubtitle: 'Fill your details or continue with social media',
    HLoginGoogle: 'Sign In with Google',
    HRegisterGoogle: 'Sign Up wiith Google',
    HForgotPassFlatButton: 'Forgot password?',
    HHomeScreenTitle: 'Welcome Dr,',
    HHomeScreenSubtitle: 'What do you want to do today?',
    HHomeScreenCalenderTitle: 'Pending appointment',
    HHomeScreenCalenderPatientName: 'Tanvir Ahmed',
    HHomeScreenCalenderDiagnosis1: 'High Blood Pressure',
    HHomeScreenCalenderDiagnosis2: 'Malaria',
    HHomeScreenAvailabilityText: 'I am Available',
    HHomeScreenAppointmentText: 'Schedule appointment calender',
    HHomeScreenCommunityText: 'Community Feed',
    HHomeScreenExploreButtonText: 'View All',
    HHomeScreenShopDevicesText: 'Shop For Devices',

}